- name: Déploiement d'Inception sur une VM Azure
  hosts: inception
  become: true
  tasks:
    - name: Installer les dépendances
      apt:
        name:
          - git
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Ajouter l'utilisateur au groupe Docker
      user:
        name: pdeshaye
        groups: docker
        append: yes
    - name: Construire les images Docker
      command:
        cmd: docker compose build
        chdir: /home/pdeshaye/ft_inception-42/srcs

    - name: Démarrer les containers
      command:
        cmd: docker compose up -d
        chdir: /home/pdeshaye/ft_inception-42/srcs

